#Modified on Mon Apr 13 15:19:43 UTC 2026
#Mon Apr 13 15:19:43 UTC 2026
database.driver=org.mariadb.jdbc.Driver
database.jndicontext=java\:/comp/env
database.jndiname=fmrdatabase
encrypt.password=ed118183-258e-4998-a715-d0761f821c4c
encrypt.salt=961317af-704e-4c37-a882-a1b49c0e092a
registry.url=http\://localhost\:8179
security.password=$2a$10$KHitofI9P3EjsY/EkleWGO6l7.ju76AYO0OM90QgS61MMqsrOBSTm
security.username=root
