#Modified on Mon Mar 30 11:03:30 UTC 2026
#Mon Mar 30 11:03:30 UTC 2026
database.driver=com.mysql.cj.jdbc.Driver
database.password=bnuHUHWu/QgVo+LCDT8ZbA\=\=
database.url=jdbc\:mysql\://fmrdatabase\:3306/fmr
database.username=fmruser
encrypt.password=ed118183-258e-4998-a715-d0761f821c4c
encrypt.salt=961317af-704e-4c37-a882-a1b49c0e092a
registry.url=http\://localhost\:8179
security.password=$2a$10$fkzvqsH.KZBH.QNRmQc.6OgHj1p.Y3d6uqftKNVY.AhSp4S/xKs9S
security.username=root
