#Modified on Fri Apr 10 12:26:12 UTC 2026
#Fri Apr 10 12:26:12 UTC 2026
database.driver=org.mariadb.jdbc.Driver
database.jndicontext=java\:/comp/env
database.jndiname=fmrdatabase
encrypt.password=ed118183-258e-4998-a715-d0761f821c4c
encrypt.salt=961317af-704e-4c37-a882-a1b49c0e092a
registry.url=http\://localhost\:8179
security.password=$2a$10$xVKaBmoUWPGVmcPtbJikdevrVTxj8hC3WmtCEuLt5oQypKkwj23Ny
security.username=root
